# Generated by Django 4.2.25 on 2025-10-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student1',
            fields=[
                ('stu_id', models.IntegerField(primary_key=True, serialize=False)),
                ('stu_name', models.CharField(max_length=50)),
                ('stu_branch', models.CharField(max_length=20)),
                ('stu_mob', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
