# Generated by Django 4.2.25 on 2025-10-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coders',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('email', models.CharField(default='user@gmail.com', max_length=20)),
            ],
        ),
    ]
