# Generated by Django 4.2.25 on 2025-10-27 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serializer_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coders',
            old_name='id',
            new_name='c_id',
        ),
    ]
